### PR TITLE
HPCC-28119 Fix compile error on modern compilers

### PR DESCRIPTION
**Pull request by xwang2713**
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexis.com>

Tested on Jenkins: http://10.224.20.18/view/Ubuntu-22.04/job/CE-Candidate-Nagiosmonitoring-jammy/CE=ubuntu-22.04-amd64-aws-ris/4/console

@Michael-Gardner please review

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 looks good and built locally. looks good to go.

**Review by richardkchapman — CHANGES_REQUESTED** [review]
Are you sure this is not supposed to be a null check?

**Comment by xwang2713** [comment]
I will change to a more logic comparison

**Comment by richardkchapman** [comment]
Change seems more plausible, but the commit title is wrong

**Comment by xwang2713** [comment]
Changed PR title as well as commit message to "HPCC-28119 replace with StringBuffer.length() to test string size"

**Comment by richardkchapman** [comment]
The commit title should be "Fix compile error on modern compilers" or similar - the details of what changed inside the source are obtained by comparing the code before and after if needed, but that's of no interest to any user looking at change logs

**Comment by xwang2713** [comment]
Fixed

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
