### PR TITLE
HPCC-23794 remove manually detectin C/C++ compiler version

### PR DESCRIPTION
**Pull request by xwang2713**
cmake will automatically generate full compiler version for C and C++
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexis.com>

@Michael-Gardner please review

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Looks good.  Tests on jenkins fixed the issue here

**Comment by xwang2713** [comment]
@richardkchapman  this is ready to merged.

**Comment by richardkchapman** [comment]
Is this needed in 7.8.0?

**Comment by xwang2713** [comment]
base changed

**Comment by richardkchapman** [comment]
Can you squash this to a single commit please

**Comment by xwang2713** [comment]
A new is created

**Pull request closed without merging**
