### PR TITLE
HPCC-10089  Nagios Eclwatch integration

### PR DESCRIPTION
**Pull request by garonsky**
- Generate nagios escalation commands and configurations
	- Escalations/notification to eclwatch
	- More configuration options when generating nagios service configs
	- Some minor bug fixes

Signed-off-by: Gleb Aronsky <gleb.aronsky@lexisnexis.com>

### CODE REVIEW

**Comment by garonsky** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@garonsky generally looks good. Several questions.

**Comment by garonsky** [comment]
@wangkx all suggested changes have been made.  Please review.

**Comment by wangkx** [comment]
@garonsky looks fine for me.

**Comment by richardkchapman** [comment]
Is this targeting 5.4 or 6.0?

**Comment by garonsky** [comment]
5.4

**Pull request merged**
