### PR TITLE
HPCC-14218 - Add options for multiple credentials

### PR DESCRIPTION
**Pull request by garonsky**
- Add support for multiple credentials to target different esps
- Improve comment section in generated files
Signed-off-by: Gleb Aronsky <gleb.aronsky@lexisnexis.com>

### CODE REVIEW

**Comment by garonsky** [comment]
@wangkx please review

**Comment by garonsky** [comment]
Changes made based on comments.
@richardkchapman this is ready to pull.

**Comment by richardkchapman** [comment]
@wangkx Please review

**Comment by wangkx** [comment]
@richardkchapman looks fine.

**Pull request merged**
