### PR TITLE
HPCC-17687 Expand deprecated loop definition to for(;;)

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@rpastrana Two commits.  One resolves the loop deprecation issue in the builds, the other resolves an issue with check_sasha using a symbol with no implementation.

**Comment by rpastrana** [comment]
@Michael-Gardner change looks reasonable.

**Comment by Michael-Gardner** [comment]
@richardkchapman Please merge.

**Comment by Michael-Gardner** [comment]
@richardkchapman Ming says we might need to retag also.

**Pull request merged**
